In [58]:
import pandas as pd
import numpy as np

In [59]:
def show_head_tail(df):
    display(df.head(5))
    display(df.tail(5))

In [60]:
def show_max(df, column):
    print("Máximo valor em", column)
    display(df[df[column] == df[column].max()])
    
def show_min(df, column):
    print("Mínimo valor em", column)
    display(df[df[column] == df[column].min()])

In [61]:
def listar_valores_unicos(df, coluna):
    print(f"\nValores únicos na coluna '{coluna}':")
    print(df[coluna].unique())
    print(df[coluna].value_counts())

In [62]:
faturamento_br = pd.read_csv('data/faturamento mel/Faturamento R$ - Mel de Abelha - Brasil - 1974 2023.csv')
faturamento_br

,Sigla,Código,Brasil,1974,1975,1976,1977,1978,1979,1980,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,BR,0,Brasil,51894.66447,86042.301405,96464.278622,67008.559635,64622.661775,69099.910749,67484.412287,...,232378.888835,246313.199961,299400.116727,314682.624086,294926.532107,278263.994179,334416.942334,397418.252929,422375.012785,371282.235818

In [63]:
melted_faturamento_br = pd.melt(faturamento_br.drop(columns=['Sigla', 'Código']), id_vars=['Brasil'], var_name='Ano', value_name='faturamento (R$)')
show_head_tail(melted_faturamento_br)

   Brasil   Ano  faturamento (R$)
0  Brasil  1974      51894.664470
1  Brasil  1975      86042.301405
2  Brasil  1976      96464.278622
3  Brasil  1977      67008.559635
4  Brasil  1978      64622.661775

    Brasil   Ano  faturamento (R$)
45  Brasil  2019     278263.994179
46  Brasil  2020     334416.942334
47  Brasil  2021     397418.252929
48  Brasil  2022     422375.012785
49  Brasil  2023     371282.235818

In [64]:
producao_br = pd.read_csv('data/producao mel/Producao Kg - Mel de Abelha - Brasil - 1974 2023.csv')
producao_br

,Sigla,Código,Brasil,1974,1975,1976,1977,1978,1979,1980,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,BR,0,Brasil,4129244,5492289,5902086,5333668,6419895,7283057,6202119,...,38481416,37859193,39677393,41695747,42407352,46088931,52493135,55678534,62494156,64188949

In [65]:
melted_producao_br = pd.melt(producao_br.drop(columns=['Sigla', 'Código']), id_vars=['Brasil'], var_name='Ano', value_name='produção (Kg)')
show_head_tail(melted_producao_br)

   Brasil   Ano  produção (Kg)
0  Brasil  1974        4129244
1  Brasil  1975        5492289
2  Brasil  1976        5902086
3  Brasil  1977        5333668
4  Brasil  1978        6419895

    Brasil   Ano  produção (Kg)
45  Brasil  2019       46088931
46  Brasil  2020       52493135
47  Brasil  2021       55678534
48  Brasil  2022       62494156
49  Brasil  2023       64188949

In [66]:
mel_br = melted_producao_br.merge(melted_faturamento_br, on=['Brasil', 'Ano'],how='inner')
show_head_tail(mel_br)

   Brasil   Ano  produção (Kg)  faturamento (R$)
0  Brasil  1974        4129244      51894.664470
1  Brasil  1975        5492289      86042.301405
2  Brasil  1976        5902086      96464.278622
3  Brasil  1977        5333668      67008.559635
4  Brasil  1978        6419895      64622.661775

    Brasil   Ano  produção (Kg)  faturamento (R$)
45  Brasil  2019       46088931     278263.994179
46  Brasil  2020       52493135     334416.942334
47  Brasil  2021       55678534     397418.252929
48  Brasil  2022       62494156     422375.012785
49  Brasil  2023       64188949     371282.235818

In [67]:
show_max(mel_br,'produção (Kg)')
show_max(mel_br,'faturamento (R$)')

Máximo valor em produção (Kg)

    Brasil   Ano  produção (Kg)  faturamento (R$)
49  Brasil  2023       64188949     371282.235818

Máximo valor em faturamento (R$)

    Brasil   Ano  produção (Kg)  faturamento (R$)
48  Brasil  2022       62494156     422375.012785

In [68]:
mel_br['faturamento/Kg'] = mel_br['faturamento (R$)']/mel_br['produção (Kg)']
show_head_tail(mel_br)
show_max(mel_br,'faturamento/Kg')

   Brasil   Ano  produção (Kg)  faturamento (R$)  faturamento/Kg
0  Brasil  1974        4129244      51894.664470        0.012568
1  Brasil  1975        5492289      86042.301405        0.015666
2  Brasil  1976        5902086      96464.278622        0.016344
3  Brasil  1977        5333668      67008.559635        0.012563
4  Brasil  1978        6419895      64622.661775        0.010066

    Brasil   Ano  produção (Kg)  faturamento (R$)  faturamento/Kg
45  Brasil  2019       46088931     278263.994179        0.006038
46  Brasil  2020       52493135     334416.942334        0.006371
47  Brasil  2021       55678534     397418.252929        0.007138
48  Brasil  2022       62494156     422375.012785        0.006759
49  Brasil  2023       64188949     371282.235818        0.005784

Máximo valor em faturamento/Kg

    Brasil   Ano  produção (Kg)  faturamento (R$)  faturamento/Kg
15  Brasil  1989       16019142     413046.780794        0.025785